conda env: add scaraplate to refresh existing project
Installs scaraplate-0.2.3+g4602a26 ('3+g': 3 commits ahead of previous
tag 0.2, currently at commit 4602a26).  Nice auto version generation
tracking.

Had to use my branch of scaraplate to unpin the pyyaml version to 3, to fix the
following install error:

```
Installing collected packages: marshmallow, pyyaml, scaraplate
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 5.3.1

Pip subprocess error:
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```